### ISSUE TITLE
 Command execution error

### ISSUE THREAD

**Issue by Karkers** [Eaphan/BiProDet#11]
python -m pcdet.datasets.kitti.kitti_dataset create_kitti_infos tools/cfgs/dataset_configs/kitti_dataset.yaml

Traceback (most recent call last):
  File "/home/karker/anaconda3/envs/bp/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/karker/anaconda3/envs/bp/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/karker/PROJ/BiProDet-main/OpenPCDet/pcdet/datasets/__init__.py", line 15, in <module>
    from .argo2.argo2_dataset import Argo2Dataset
  File "/home/karker/PROJ/BiProDet-main/OpenPCDet/pcdet/datasets/argo2/argo2_dataset.py", line 7, in <module>
    from av2.utils.io import read_feather
ModuleNotFoundError: No module named 'av2'
这个av2是什么，我没有找到这个包

**Comment by Karkers** [comment]
我已经解决了。是我的python版本不对
