### ISSUE TITLE
AttributeError: 'Conv1dBlock' object has no attribute 'conv_fn'

### ISSUE THREAD

**Issue by Z-Lee-corder** [Eaphan/BiProDet#16]

**Comment by Eaphan** [comment]
Sorry for the mistake, you can pull the latest change and run it again.

**Comment by Z-Lee-corder** [comment]
Hello, I have rerun the program according to your update. The following error still occurs:

Traceback (most recent call last):
  File "/media/lizheng/Samsung/codes/BiProDet/tools/train.py", line 202, in <module>
    main()
  File "/media/lizheng/Samsung/codes/BiProDet/tools/train.py", line 154, in main
    train_model(
  File "/media/lizheng/Samsung/codes/BiProDet/tools/train_utils/train_utils.py", line 111, in train_model
    accumulated_iter = train_one_epoch(
  File "/media/lizheng/Samsung/codes/BiProDet/tools/train_utils/train_utils.py", line 47, in train_one_epoch
    loss, tb_dict, disp_dict = model_func(model, batch)
  File "/media/lizheng/Samsung/codes/BiProDet/tools/../pcdet/models/__init__.py", line 42, in model_func
    ret_dict, tb_dict, disp_dict = model(batch_dict)
  File "/home/lizheng/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/media/lizheng/Samsung/codes/BiProDet/tools/../pcdet/models/detectors/point_3dssd.py", line 17, in forward
    batch_dict = cur_module(batch_dict)
  File "/home/lizheng/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/media/lizheng/Samsung/codes/BiProDet/tools/../pcdet/models/backbones_3d/pointnet2_backbone.py", line 541, in forward
    li_xyz, li_features, li_vis, li_scores, image_x = self.SA_modules[i](
  File "/home/lizheng/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/media/lizheng/Samsung/codes/BiProDet/tools/../pcdet/ops/pointnet2/pointnet2_batch/pointnet2_modules.py", line 923, in forward
    feat_2d_to_3d = self.fuse3d_before_mlps(feat_2d_to_3d)
  File "/home/lizheng/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lizheng/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/home/lizheng/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/media/lizheng/Samsung/codes/BiProDet/tools/../pcdet/ops/pointnet2/pointnet2_batch/pointnet2_utils.py", line 575, in forward
    x = self.norm(x)
  File "/home/lizheng/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lizheng/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/nn/modules/batchnorm.py", line 135, in forward
    self._check_input_dim(input)
  File "/home/lizheng/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/nn/modules/batchnorm.py", line 408, in _check_input_dim
    raise ValueError("expected 4D input (got {}D input)".format(input.dim()))
ValueError: expected 4D input (got 3D input)

**Comment by Eaphan** [comment]
You can pull the latest change and run it again.

In a commit, we wrongly define the Conv1dBlock function.
