### ISSUE TITLE
 input_dict['segmentation'] = annos["inmodal_seg"] KeyError: 'inmodal_seg'

### ISSUE THREAD

**Issue by RickySumX** [Eaphan/BiProDet#20]
epochs:   0%|                                                                                                                                                            | 0/80 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 202, in <module>
    main()
  File "train.py", line 154, in main
    train_model(
  File "/202121622952/UPIDet/tools/train_utils/train_utils.py", line 111, in train_model
    accumulated_iter = train_one_epoch(
  File "/202121622952/UPIDet/tools/train_utils/train_utils.py", line 25, in train_one_epoch
    batch = next(dataloader_iter)
  File "/root/anaconda3/envs/upi/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/root/anaconda3/envs/upi/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 570, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/root/anaconda3/envs/upi/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/anaconda3/envs/upi/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/202121622952/UPIDet/tools/../pcdet/datasets/kitti/kitti_dataset.py", line 407, in __getitem__
    input_dict['segmentation'] = annos["inmodal_seg"]
KeyError: 'inmodal_seg'

I print（annos）,but i find annos isn't include 'inmodal_seg':
![ebb04c96f2b5e7d20599a4a078175dbe](https://github.com/Eaphan/UPIDet/assets/133204224/6f6b1a84-c4ec-4015-8a89-b392cc643192)

'name': array(['Car', 'DontCare', 'DontCare'], dtype='<U8'), 'truncated': array([ 0., -1., -1.]), 'occluded': array([ 0., -1., -1.]), 'alpha': array([  1.92, -10.  , -10.  ]), 'bbox': array([[254.08, 184.29, 360.28, 232.81],
       [583.3 , 181.83, 593.3 , 191.83],
       [500.5 , 177.94, 520.2 , 190.52]], dtype=float32), 'dimensions': array([[ 4.33,  1.48,  1.97],
       [-1.  , -1.  , -1.  ],
       [-1.  , -1.  , -1.  ]]), 'location': array([[  -10.3 ,     1.89,    24.82],
       [-1000.  , -1000.  , -1000.  ],
       [-1000.  , -1000.  , -1000.  ]], dtype=float32), 'rotation_y': array([  1.53, -10.  , -10.  ]), 'score': array([-1., -1., -1.]), 'difficulty': array([ 0, -1, -1], dtype=int32), 'index': array([ 0, -1, -1], dtype=int32), 'gt_boxes_lidar': array([[25.10887909, 10.32051182, -0.85387194,  4.33      ,  1.97      ,
         1.48      , -3.10079633]]), 'num_points_in_gt': array([163,  -1,  -1], dtype=int32)}

**Comment by Eaphan** [comment]
Please prepare KITTI Dataset as we suggested in the Readme file. "Please download them in this link and replace the original files."

**Comment by RickySumX** [comment]
Thanks for your help

**Comment by Bennyliiiiii** [comment]
@RickySumX I also encountered the same problem, have you solved it?
