### ISSUE TITLE
The demo.py file doesn't work on biprodet.yaml

### ISSUE THREAD

**Issue by amineboujnah-dev** [Eaphan/BiProDet#4]
Please provide a demo file for biprodet with 3D bounding boxes for image and point cloud.

**Comment by Eaphan** [comment]
I guess that you mean demo.py doesn't work. I have not changed it for cross-modality visualization. If you want to visualize the predicted results, you can try to save the predicted boxes and visualize them by yourself. Here are some examples:
https://github.com/kuixu/kitti_object_vis
https://github.com/yeyang1021/KITTI_VIZ_3D
https://github.com/zzzxxxttt/simple_kitti_visualization

**Comment by amineboujnah-dev** [comment]
When I tried to run demo.py I got this error :

**python3 demo.py --cfg_file cfgs/kitti_models/biprodet.yaml --ckpt biprodet_release.pth** 

Failed to load one or more CUDA extensions, performance may be hurt.
Error message: No module named 'pcdet.ops.k_nearest_neighbor._k_nearest_neighbor_cuda'
2023-02-26 11:17:30,127   INFO  -----------------Quick Demo of OpenPCDet-------------------------
2023-02-26 11:17:30,127   INFO  Total number of samples:        1
biprodet_release.pth
2023-02-26 11:17:31,394   INFO  ==> Loading parameters from checkpoint biprodet_release.pth to CPU
2023-02-26 11:17:32,029   INFO  ==> Checkpoint trained from version: pcdet+0.5.2+c0ccfb0+py56c3437
2023-02-26 11:17:32,078   INFO  ==> Done (loaded 753/753)
Traceback (most recent call last):
  File "demo.py", line 112, in <module>
    main()
  File "demo.py", line 94, in main
    for idx, data_dict in enumerate(demo_dataset):
  File "demo.py", line 48, in __getitem__
    points = np.fromfile(self.sample_file_list[index], dtype=np.float32).reshape(-1, 4)
FileNotFoundError: [Errno 2] No such file or directory: 'demo_data'

**Comment by amineboujnah-dev** [comment]
Thanks a lot! Can you help with running the model for real time object detection from lidar and camera sensors ?
